name: API Commit Stage

on: 
  - pull_request

permissions:
  checks: write

jobs:
  commit-stage-checks:
    name: Commit Stage Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out branch
        uses: actions/checkout@v3
        with:
          path: head
      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'head/*.oas.yaml'
          spectral_ruleset: 'head/.spectral.yaml'
      - name: Check out master branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: base
      - name: "Run breaking change check (OpenAPITools/openapi-diff)"
        id: diff_state
        uses: swimmwatch/openapi-diff-action@v1.0.0
        with:
          old-spec: base/api.oas.yaml
          new-spec: head/api.oas.yaml
          json: "out.json"
          markdown: "out.md"
      - name: "Upload OpenAPI-diff report"
        uses: actions/upload-artifact@v3
        with:
          name: diff-reports
          path: |
            ./out.md
            ./out.json

      
        


