name: API Commit Stage

on: 
  - pull_request

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        