name: API Commit Stage

on: 
  - pull_request

permissions:
  actions: write

jobs:
  commit-stage-checks:
    name: Commit Stage Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        